#!/usr/bin/env perl
# Dotfiles setup script
# Symlink from _config.yml

use strict;
use warnings;

use Cwd qw(cwd);
use YAML::XS qw(LoadFile);
use File::Basename;
use File::Path qw(make_path);

my $user = getpwuid($<);
my $home_dir = "/Users/${user}";
my $current_dir = cwd;
my $data = LoadFile("${current_dir}/_config.yml");

my $key;
my $value;
my %links = %{$data->{links}};
while (($key, $value) = each (%links)) {
    $value = $links{$key};
    $key =~ s/__home__/${home_dir}\//ig;

    my $dir = dirname($key);
    if ( ! -d "$dir") {
        make_path($dir);
    }

    unlink($key);
    symlink("${current_dir}/${value}", $key);

    if ($key =~ m(^bin\/)) {
        # Make exe if bin script.
        chmod 0755, $value;
    }

    print "[+] ${value} linked to ${key}\n";
}
