#!/bin/bash
# File  : brew
# Author: Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date  : 26.10.2019

set -e -x

brew update

brew install \
  postgresql \
  tmux \
  redis \
  nnn \
  lazygit \
  lazydocker \
  git \
  python3 \
  ddgr \
  vim \
  wget \
  yabai \
  zsh \
  mysql \
  macvim \
  sqlite \
  fzf \
  htop \
  exa \
  curl \
  bash \
  gnu-sed \
  tree \
  jsonnet \
  chunkwm \
  xclip

brew cask install \
  sequel-pro \
  docker \
  alacritty \
  slack \
  alfred \
  ngrok \
  firefox \
  filezilla
