#!/usr/bin/env perl
# File  : do-symlink.pl
# Author: Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date  : 23.12.2019
#
# Symlink
#

use Cwd qw(cwd);
use YAML::XS qw(LoadFile);

my $current_dir = cwd;
my $user = getlogin;
my $root = "/Users/${user}";

my $data = LoadFile("config.yml");

# Directories.
my @directories = @{$data->{directories}};
foreach $dir (@directories) {
    $dir =~ s/__root__/${root}\//ig;
    mkdir -p $dir unless -d $dir;
}

# Symlinks.
my %links = %{$data->{links}};
while (($key, $value) = each (%links)) {
    $value = $links{$key};
    $key =~ s/__root__/${root}\//ig;
    unlink($key);
    symlink("${current_dir}/${value}", $key);
    if ($key=~ m(^bin\/)) {
        # Make exe if bin script.
        chmod 0755, $value;
    }
    print "[+] ${value} linked to ${key}\n";
}
