#!/bin/bash
# File  : install
# Author: Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date  : 23.12.2019
#
# Install all
#

function setup() {
    which -s brew
    if [[ $? != 0 ]]; then
        echo "[+] Installing Homebrew"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        echo "[+] Updating Homebrew"
        brew update
    fi

    echo "[+] Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    echo "[+] Installing softwares"
    perl $PWD/brew

    echo "[+] Installing python packages"
    pip3 install -r pip/requirements.txt

    echo "[+] Setting up macOS configs"
    source $PWD/macos/macos

    echo "[+] Initiating and updating submodules"
    git submodule init && git submodule update

    echo "[+] Setting up symlinks"
    perl $PWD/symlink

    echo "***** ALL DONE *****"
}

case "$OSTYPE" in
    darwin*)
        setup
        ;;
    *)
        echo "This script needs to run on macOS"
        ;;
esac
exit 0
