* smallwat3r's dotfiles

Feel free to pick whatever you want from this repo, but note it has been mostly created for my personal use and its updated very frequently. Use at your own risks and please create back-ups of your current set-up if you intend to use the Makefile. Dotfiles are managed by GNU Stow.

Those dotfiles are maintained for different platforms because I'm using multiple machines with different OSes.

- Mac OS
- Arch with i3
  - GPD Pocket 3, running Arch with i3 (need some specific additional patches and configs)
- Fedora
- Ubuntu

Hence why the stow targets are divided into multiple different directories.

- *Cross platform* configurations can be found under ~cross-platform/~, it includes things like zsh, emacs, ssh, binaries etc. All its content "should be" platform agnostic.
- *Macbook* specific configurations can be found under ~macos/~ and ~macos-root/~.
- *Arch* specific configurations can be found under ~arch/~ and ~arch-root/~.
  - *GPD Pocket 3* (running on Arch) specific configurations can be found in ~gpd-arch/~ and ~gpd-arch-root/~. It includes stowing the generic ~arch/~ and ~arch-root/~ configs, but adds various tweaks to ensure the GPD behaves nicely on Arch Linux (screen rotation and resolution, touchscreen support, X11 configs etc).
- *Fedora* specific configurations can be found under ~fedora/~.

Clone this repo into your home directory.

#+begin_src shell
(cd $HOME && git clone https://github.com/smallwat3r/dotfiles.git)
#+end_src

** Makefile

To symlink all dotfiles (will automatically detect the OS and system for which directories to stow)
#+begin_src shell
make symlink
#+end_src

To discover other commands
#+begin_src shell
make help
#+end_src

** Emacs

I'm using Emacs 30.x with [[https://github.com/doomemacs/doomemacs][Doom Emacs]].

Most of my config should be cross platform and can be found in this repo at: [[cross-platform/.doom.d]].

*** Install Emacs
**** Mac OS
#+begin_src shell
brew tap d12frosted/emacs-plus && brew install emacs-plus@30
#+end_src

**** Arch
#+begin_src shell
sudo pacman -S emacs-nativecomp
#+end_src

**** Fedora
#+begin_src shell
sudo dnf install emacs
#+end_src


*** Install Doom
#+begin_src shell
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src
