* smallwat3r’s dotfiles

This repository contains my personal dotfiles. You are welcome to reuse any part of it, but note that it is tailored to my own workflow and updated frequently. Use at your own risk, and make sure to back up your existing setup before using the provided Makefile.
Dotfiles are managed with GNU Stow.

These configurations support multiple platforms because I use several machines with different operating systems:

- macOS
- Fedora

As a result, the Stow targets are split across multiple directories.

- *Cross-platform* configurations are located under ~cross-platform/~.
  This includes items such as zsh, Emacs, SSH, and binaries. Everything here *should* be platform-agnostic.
- *macOS*-specific configurations are under ~macos/~ and ~macos-root/~.
- *Fedora*-specific configurations are under ~fedora/~.

Clone this repository into your home directory:

#+begin_src shell
(cd $HOME && git clone https://github.com/smallwat3r/dotfiles.git)
#+end_src

** Makefile

To symlink all dotfiles (the Makefile automatically detects the OS and selects the appropriate Stow targets):

#+begin_src shell
make symlink
#+end_src

To list available commands:

#+begin_src shell
make help
#+end_src

** Emacs

I use Emacs 30.x with [[https://github.com/doomemacs/doomemacs][Doom Emacs]].
Most of my configuration is cross-platform and stored under [[cross-platform/.doom.d]] in this repository.

*** Installing Emacs

**** macOS
#+begin_src shell
brew tap d12frosted/emacs-plus && brew install emacs-plus@30
#+end_src

**** Fedora
#+begin_src shell
sudo dnf install emacs
#+end_src

*** Installing Doom Emacs

#+begin_src shell
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src
