* smallwat3r's dotfiles

Personal dotfiles managed with [[https://www.gnu.org/software/stow/][GNU Stow]].

Feel free to reuse any part of this repository, but note that it is tailored to my own workflow and updated frequently. Back up your existing setup before using the provided Makefile.

** Requirements

- [[https://www.gnu.org/software/stow/][GNU Stow]]

** Installation

Clone into your home directory:

#+begin_src shell
git clone https://github.com/smallwat3r/dotfiles.git ~/dotfiles
#+end_src

On a fresh Fedora install, provision everything in one go. This enables the
third-party repositories, installs the packages listed in ~packages.dnf.txt~ and
~packages.flatpak.txt~, enables the system services they need, stows the
dotfiles and sets up the Emacs config and firefox-sway (see below). It is safe to
re-run.

#+begin_src shell
cd ~/dotfiles && make bootstrap
#+end_src

On an already provisioned machine, just stow the dotfiles (user configs to
~$HOME~, system configs to ~/~ with sudo):

#+begin_src shell
cd ~/dotfiles && make stow
#+end_src

Other available commands:

#+begin_src shell
make unstow     # remove all symlinks
make dry-run    # preview changes without modifying the filesystem
make help       # list available commands
#+end_src

** Structure

| Directory | Description                                              |
|-----------+----------------------------------------------------------|
| ~home~    | User configs, stowed to ~$HOME~ (zsh, git, sway, etc)    |
| ~root~    | System configs, stowed to ~/~ with sudo (udev rules, etc) |

These dotfiles target Fedora with sway. The macOS configuration was retired, it
is preserved at the ~macos-last~ git tag.

** Emacs

Emacs configuration is managed in a [[https://github.com/smallwat3r/emacs][separate repository]]. ~make bootstrap~
sets it up, to do it by hand:

#+begin_src shell
git clone https://github.com/smallwat3r/emacs.git ~/.config/smallwat3r-emacs
ln -s ~/.config/smallwat3r-emacs ~/.emacs.d
#+end_src

** Firefox

Firefox is stripped down for sway by [[https://github.com/smallwat3r/firefox-sway][firefox-sway]], which also provides the
~ff-launcher-*~ scripts bound in the sway config. ~make bootstrap~ sets it up, to
do it by hand:

#+begin_src shell
git clone https://github.com/smallwat3r/firefox-sway.git ~/code/firefox-sway
make -C ~/code/firefox-sway install
#+end_src
