* smallwat3r's dotfiles

Feel free to pick whatever you want from this repo, but note it has been mostly
created for my personal use and its updated very frequently. Use at your own risks
and please create back-ups of your current set-up if you intend to use the Makefile.
Dotfiles are managed by GNU Stow.

Those dotfiles are maintained for different platforms because I'm using multiple machines
with different OSes.

- Macbook 13
- Arch Linux with i3
- GPD Pocket 3, running Arch with i3 (need some specific additional patches and configs)

Hence why the stow targets are divided into multiple different directories.

Cross platform configurations can be found under ~cross-platform~, it includes things like
zsh, emacs, ssh, bash scripts. Those "should be" platform agnostic.

Macbook specific configurations can be found under ~macos~ and ~macos-root~.

Arch Linux specific configurations can be found under ~arch~ and ~arch-root~.

GPD Pocket 3 specific configurations can be found in ~gpd-arch~ and ~gpd-arch-root~. It includes
stowing the generic ~arch~ and ~arch-root~ configs, but also includes various tweaks to make the
GPD running correctly on Arch Linux (screen rotation and resolution, touchscreen support, X11
configs etc).

Clone this repo into your home directory.

#+begin_src shell
(cd $HOME && git clone https://github.com/smallwat3r/dotfiles.git)
#+end_src

*Makefile usage:*

To symlink all dotfiles (will automatically detect the OS and system for which directories to stow)
#+begin_src shell
make symlink
#+end_src

To discover other commands
#+begin_src shell
make help
#+end_src

** Emacs

Install Emacs, I'm using Emacs 28 with native compilation (=gccEmacs=)

For macOS:
#+begin_src shell
brew tap d12frosted/emacs-plus && brew install emacs-plus@28 --with-native-comp
#+end_src

For Arch Linux:
#+begin_src shell
sudo pacman -S emacs-nativecomp
#+end_src

Then,

Install Doom in a custom =~/.emacs.doom= directory which allows me to use [[https://github.com/plexus/chemacs2][Chemacs2]]
#+begin_src shell
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.doom
~/.emacs.doom/bin/doom install
#+end_src

Install Chemacs2 and move aside any existing config
#+begin_src shell
[ -f ~/.emacs ] && mv ~/.emacs ~/.emacs.bak
[ -d ~/.emacs.d ] && mv ~/.emacs.d ~/.emacs.legacy
git clone https://github.com/plexus/chemacs2.git ~/.emacs.d
#+end_src
