* smallwat3r's dotfiles

Personal dotfiles managed with [[https://www.gnu.org/software/stow/][GNU Stow]].

Feel free to reuse any part of this repository, but note that it is tailored to my own workflow and updated frequently. Back up your existing setup before using the provided Makefile.

** Requirements

- [[https://www.gnu.org/software/stow/][GNU Stow]]

** Installation

Clone into your home directory:

#+begin_src shell
git clone https://github.com/smallwat3r/dotfiles.git ~/dotfiles
#+end_src

Stow all dotfiles (the Makefile detects the OS and selects the appropriate targets):

#+begin_src shell
cd ~/dotfiles && make stow
#+end_src

Other available commands:

#+begin_src shell
make unstow     # remove all symlinks
make dry-run    # preview changes without modifying the filesystem
make help       # list available commands
#+end_src

** Structure

| Directory | Description                                              |
|-----------+----------------------------------------------------------|
| ~home~    | User configs, stowed to ~$HOME~ (zsh, git, sway, etc)    |
| ~root~    | System configs, stowed to ~/~ with sudo (udev rules, etc) |

These dotfiles target Fedora with sway. The macOS configuration was retired, it
is preserved at the ~macos-last~ git tag.

** Emacs

Emacs configuration is managed in a [[https://github.com/smallwat3r/emacs][separate repository]].

#+begin_src shell
git clone https://github.com/smallwat3r/emacs.git ~/.config/smallwat3r-emacs
ln -s ~/.config/smallwat3r-emacs ~/.emacs.d
#+end_src
