#!/usr/bin/env bash
# Copy last commit hash to clipboard on commit

copy_clipboard() {
    if [[ "$OSTYPE" =~ ^darwin ]]; then
        pbcopy <<< "$1"
    elif command -v wl-copy >/dev/null 2>&1; then
        wl-copy <<< "$1"
    elif command -v xclip >/dev/null 2>&1 && [[ -n "$DISPLAY" ]]; then
        xclip -selection clipboard <<< "$1"
    else
        echo "$1"
    fi
}

copy_clipboard "$(git log -1 --format=%h)"
