alias c="clear"
alias p="pwd"
alias l="ls -pFf"
alias ll="ls -la"
alias ls.="ls -pF -d .*"
alias ls="ls -pF"
alias sl="ls -pF"
alias lss="ls -la | grep --color=never '->'"
alias mkdir="mkdir -pv"
alias qq="exit"
alias g="git"
