#!/bin/bash
# File  : brew
# Author: Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date  : 26.10.2019

packages=(tmux redis nnn lazygit lazydocker git python3 ddgr vim wget zsh
    mysql sqlite fzf htop exa curl bash gnu-sed tree jsonnet chunkwm xclip jq)

casks=(sequel-pro docker alacritty slack alfred ngrok firefox fontforge)


for p in "${packages[@]}"; do
    if ! brew ls --versions $p >/dev/null; then
        echo "[+] installing $p"
        brew install $p
    else
        echo "[.] $p already installed"
    fi
done

for c in "${casks[@]}"; do
    if ! brew cask list | grep -ri $c >/dev/null; then
        name=$(echo $c | sed -E 's/[-_]+/ /g')
        if ! ls /Applications | grep -ri "$name" >/dev/null; then
            echo "[+] installing $c"
            brew cask install $c
        else
            echo "[.] $c seems already installed in /Applications"
        fi
    else
        echo "[.] $c already installed via Homebrew"
    fi
done

# Macvim fix
if ! brew ls --versions "macvim" >/dev/null; then
    echo "[+] installing macvim"
    brew unlink vim
    brew install macvim
    brew link vim
else
    echo "[.] macvim already installed"
fi
