" File              : vimrc
" Author            : smallwat3r
" Date              : Wed  7 Aug 19:49:35 2019

execute pathogen#infect()

" Source files
" ----------------------------------------------------------------
source ~/dotfiles/vim/settings.vim
source ~/dotfiles/vim/keybindings.vim
source ~/dotfiles/vim/functions.vim
source ~/dotfiles/vim/plugin-config.vim
