#!/usr/bin/env perl
# Dotfiles setup script
# Install brew and cask from _config.yml

use strict;
use warnings;

use Cwd qw(cwd);
use YAML::XS qw(LoadFile);

my $current_dir = cwd;
my $data = LoadFile("${current_dir}/_config.yml");

my $brew;
my @brews=@{$data->{brew}};
foreach $brew (@brews) {
    system("sh", "${current_dir}/_install/do-brew.sh", $brew);
}

my $cask;
my @casks=@{$data->{cask}};
foreach $cask (@casks) {
    system("sh", "${current_dir}/_install/do-cask.sh", $cask);
}
