add_newline = false

[character]
symbol = "%%"
vicmd_symbol = ";;"
error_symbol = "✗"
use_symbol_for_status = true

[directory]
truncation_length = 7
style = "white"

[git_branch]
symbol = "🌱 "
truncation_symbol = ""
style = "white"

[git_commit]
commit_hash_length = 7
only_detached = false
style = "white"

[git_state]
progress_divider = " of "
style = "white"

[git_status]
prefix = ""
suffix = ""
style = "red"
