add_newline = false
prompt_order=["directory","git_commit","git_branch","git_status","character"]

[character]
symbol = "%%"
style_success = "white"
style_failure = "red"
vicmd_symbol = ";;"
error_symbol = "%%"
use_symbol_for_status = true

[directory]
truncation_length = 2
style = "white"

[git_branch]
symbol = ""
style = "white"

[git_commit]
commit_hash_length = 7
only_detached = true
style = "white"

[git_status]
prefix = "["
suffix = "] "
style = "white"

[cmd_duration]
min_time = 500
style = "white"
