# Appearance

font pango:Ocrab Nerd Font Mono 9
titlebar_padding 4 1

default_border pixel 2
hide_edge_borders smart
gaps inner 0
gaps outer 0

floating_minimum_size 75 x 50
floating_maximum_size 0 x 0

workspace_layout tabbed
default_orientation auto

# Window colors (Windows 98)
#                       border  bg      text    indicator child_border
client.focused          #3e4e6e #3e4e6e #ffffff #3e4e6e   #3e4e6e
client.focused_inactive #c0c0c0 #808080 #c0c0c0 #808080   #c0c0c0
client.unfocused        #c0c0c0 #808080 #c0c0c0 #808080   #c0c0c0
client.urgent           #c0c0c0 #aa0000 #ffffff #aa0000   #c0c0c0

output * bg #008080 solid_color
