# Appearance

font pango:Ocrab Nerd Font Mono 9
titlebar_padding 4 1

default_border pixel 2
hide_edge_borders smart
gaps inner 0
gaps outer 0

floating_minimum_size 75 x 50
floating_maximum_size 0 x 0

workspace_layout tabbed
default_orientation auto

# Window colors (old school), variables set in 00-theme.conf
#                       border bg      text   indicator child_border
client.focused          $focus $focus  $white $navy     $navy
client.focused_inactive $face  $shadow $face  $shadow   $face
client.unfocused        $face  $shadow $face  $shadow   $face
client.urgent           $face  $urgent $white $urgent   $face

output * bg $teal solid_color
