# Media keys

bindsym XF86AudioRaiseVolume exec swayosd-client --output-volume raise
bindsym XF86AudioLowerVolume exec swayosd-client --output-volume lower
bindsym XF86AudioMute exec swayosd-client --output-volume mute-toggle
bindsym XF86AudioMicMute exec swayosd-client --input-volume mute-toggle
bindsym XF86MonBrightnessUp exec swayosd-client --brightness raise
bindsym XF86MonBrightnessDown exec swayosd-client --brightness lower

# Screenshots
bindsym Print exec screenshot region
bindsym Ctrl+Print exec screenshot window
bindsym Shift+Print exec screenshot full

# Screen recording
bindsym $mod+Print exec recording region
bindsym $mod+Ctrl+Print exec recording window
bindsym $mod+Shift+Print exec recording full
bindsym $mod+Escape exec recording stop
