#!/usr/bin/env bash

# Prevent from committing any line (or filename) containing the string NOCOMMIT.
if git diff --cached -- . ':(exclude)**/git/templates/hooks/pre-commit' | grep '^[+d].*NOCOMMIT'; then
    echo
    echo 'Adding line containing NOCOMMIT'
    exit 1
fi
