#!/usr/bin/env ruby

brew "antigen"
brew "aspell"
brew "bash"
brew "bitwarden-cli"
brew "cmake"
brew "coreutils"
brew "curl"
brew "dockutil"
brew "eslint"
brew "fd"
brew "fzf"
brew "git"
brew "gnupg"
brew "go"
brew "htop"
brew "isync"
brew "jq"
brew "lua"
brew "make"
brew "msmtp"
brew "nmap"
brew "notmuch"
brew "nvm"
brew "openssl"
brew "pandoc"
brew "pass"
brew "pinentry-mac"
brew "python@3.10"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "stow"
brew "swaks"
brew "tmux"
brew "wget"
brew "yarn"
brew "zsh"

# Taps

tap "smallwat3r/scripts"
brew "shhh"
brew "sketch"
brew "synonym"
brew "tubestatus"

# tap "teamookla/speedtest"
# brew "speedtest"

# tap "heroku/brew"
# brew "heroku"

# tap "homebrew/cask-fonts"
# brew "font-fantasque-sans-mono-noloopk"

# tap "johanhaleby/kubetail"
# brew "kubetail"

# Save screen display arrangement
# tap "jakehilborn/jakehilborn"
# brew "displayplacer"

# Casks

cask_args appdir: '/Applications'

cask "alacritty"
cask "bitwarden"
cask "docker"
cask "google-chrome"
cask "gpg-suite"
cask "hammerspoon"
cask "keybase"
cask "slack"

# cask "alfred"
# cask "mucommander"
# cask "nordvpn"
# cask "signal"
# cask "tunnelblick"
# cask "flycut"

# tap "homebrew/cask-versions"
# cask 'sequel-pro-nightly'
