#!/usr/bin/env python3
import platform
import sys
from contextlib import suppress

if platform.system() == "Darwin":
    print("macos")
    sys.exit(0)

with suppress(FileNotFoundError), open("/etc/os-release") as f:
    for line in f:
        if line.startswith("ID="):
            print(line.split("=")[1].strip().strip('"'))
            sys.exit(0)

print("unknown")
sys.exit(1)
