#!/usr/bin/env bash

[[ "$OSTYPE" == darwin* ]] && echo macos && exit 0

for id in fedora:dnf ubuntu:apt arch:pacman; do
  distro=${id%%:*}
  pkg=${id##*:}
  if command -v "$pkg" &>/dev/null; then
    echo "$distro"
    exit 0
  fi
done

echo unknown
exit 1
