#!/usr/bin/env python3
import platform
import shutil
import sys

if platform.system() == "Darwin":
    print("macos")
    sys.exit(0)

for distro, cmd in (
    ("fedora", "dnf"),
    ("ubuntu", "apt"),
    ("arch", "pacman"),
):
    if shutil.which(cmd):
        print(distro)
        sys.exit(0)

print("unknown")
sys.exit(1)
