#!/usr/bin/env python3
import os
import sys

BOARD_VENDOR = "/sys/devices/virtual/dmi/id/board_vendor"

if not os.path.exists(BOARD_VENDOR):
    sys.exit(1)

with open(BOARD_VENDOR, encoding="utf-8") as file:
    if file.read().rstrip("\n") != "GPD":
        sys.exit(1)
