#!/usr/bin/env python3
import sys
from pathlib import Path
from contextlib import suppress

vendor_file = Path("/sys/devices/virtual/dmi/id/board_vendor")
with suppress(FileNotFoundError):
    if vendor_file.read_text().rstrip("\n") == "GPD":
        print("Yes")
        sys.exit(0)
print("No")
sys.exit(1)
