#!/usr/bin/env bash
# Docker get IP

if [[ -z "$1" ]]; then
  printf 'Please specify an image.\n'
else
  docker inspect --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' \
    "$(docker ps | grep "$1" 2>/dev/null | cut -d ' ' -f1)" 2>/dev/null \
    || printf 'Cannot find %s\n' "$1" >&2
fi
