#!/usr/bin/env bash
# Copy public key to clipboard

if [[ "$OSTYPE" =~ ^darwin ]]; then
  more "${HOME}/.ssh/id_rsa.pub" | pbcopy
else
  more "${HOME}/.ssh/id_rsa.pub" | xclip -selection clipboard
fi

printf 'Public key copied to clipboard.\n'
