#!/usr/bin/env zsh
# Open in file manager

if is_macos; then
  program="open"
elif has xdg-open; then
  program="xdg-open"
else
  printf "Can't find an appropriate file opener\n" >&2
  return 127
fi

# if no arguments, open current directory
if [[ $# -eq 0 ]]; then
  "$program" .
else
  "$program" "$@"
fi
