#!/bin/bash
#
# Functions
#

# open current directory or the one specified
o() {
    if [ $# -eq 0 ]; then
        open .
    else
        open "$@"
    fi
}

# search from current dir
search() {
    grep -rnIi "$1" . --color
}

# create and enter directory
mkd() {
    mkdir -p "$@" && cd "$@"
}

# preview csv files.
# source: http://stackoverflow.com/questions/1875305/command-line-csv-viewer
csvpreview() {
    sed 's/,,/, ,/g;s/,,/, ,/g' "$@" | column -s, -t | less -#2 -N -S
}

# Show Wi-Fi Network Passwords
# Exchange SSID with the SSID of the access point you wish to query the password from.
# https://github.com/ahmadawais/dotFiles/blob/7e5b5b632a61837917a5f6194b1929283a43ec91/.zshrc#L2621
wifipass() {
    security find-generic-password -D "AirPort network password" -a "$@" -gw
}

# extract file.
# source: http://nparikh.org/notes/zshrc.txt
extract() {
    if [ -f $1 ]; then
        case $1 in
        *.tar.bz2) tar -jxvf $1 ;;
        *.tar.gz) tar -zxvf $1 ;;
        *.bz2) bunzip2 $1 ;;
        *.dmg) hdiutil mount $1 ;;
        *.gz) gunzip $1 ;;
        *.tar) tar -xvf $1 ;;
        *.tbz2) tar -jxvf $1 ;;
        *.tgz) tar -zxvf $1 ;;
        *.zip) unzip $1 ;;
        *.ZIP) unzip $1 ;;
        *.pax) cat $1 | pax -r ;;
        *.pax.Z) uncompress $1 --stdout | pax -r ;;
        *.rar) unrar x $1 ;;
        *.Z) uncompress $1 ;;
        *) echo "'$1' cannot be extracted/mounted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
