#!/bin/bash

# open current directory or the one specified
o() {
    if [ $# -eq 0 ]; then
        open .
    else
        open "$@"
    fi
}

# search from current dir
search() {
    grep -rnIi "$1" . --color
}

# preview csv files. source: http://stackoverflow.com/questions/1875305/command-line-csv-viewer
csvpreview() {
    sed 's/,,/, ,/g;s/,,/, ,/g' "$@" | column -s, -t | less -#2 -N -S
}
