#!/usr/bin/env bash
# Open in file manager

if [[ "$OSTYPE" == darwin* ]]; then
  program="open"
elif command -v xdg-open >/dev/null 2>&1; then
  program="xdg-open"
else
  printf "Can't find an appropriate file opener\n" >&2
  exit 127
fi

# if no arguments, open current directory
if [[ $# -eq 0 ]]; then
  "$program" .
else
  "$program" "$@"
fi
