#!/usr/bin/env bash
# Open in file manager

if [[ "$OSTYPE" =~ ^darwin ]]; then
  _program=open
else
  if [ -f /usr/bin/pcmanfm ]; then
    _program=pcmanfm
  elif [ -f /usr/bin/nautilus ]; then
    _program=nautilus
  else
    printf 'Can'\''t find a file manager\n' >&2
    exit 1
  fi
fi

if [[ $# -eq 0 ]]; then
  "$_program" .
else
  "$_program" "$@"
fi
